import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Marcus Atencio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h1 className="bg-blue-700">Hello</h1>
        </section>
      </main>
    </>
  )
}
